* C++ Project Template

  A C++ Project Template. 
  Because you should concentrate on the important parts.

** Introduction
This is a project template for C++.
Making files, folders, CMakeLists.txt and all the boring stuff: done and ready to go.


** How to use 
1. forking - 
   fork this project and use it. If you are really lazy.
   The project will appear as forked

2. cloning - 
   Clone this project and use it as you wish.
   The project will appear as cloned.
   
3. download -
   Download and unzip the project.
  
** How to contribute
This project is open for contribution.
Send me push requests any time you have a good idea.
Please describe reasons for additions or fixes.

I would really appreciate contributions from experienced CMakeLists.txt users.


** Licence

MIT License

Copyright (c) 2017 Red-Portal

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

