* C++ Project Template

  Because you should concentrate on the important parts.

** Introduction
This project is a project template for C++
Making files, folders, CMakeLists.txt and all the dirty stuff.
If you are too lazy to setup your project, this is for you.


** How to use 
1. forking
   fork this project and use it. This if you are really lazy.

2. cloning
   if you do not want this project to appear as forked,
   clone this project and use it as you wish.

  
** How to contribute
This project is open for contribution.
Send me push requests any time you have a good idea.
Please describe reasons for additions or fixes.

I would really appreciate contributions from experienced CMakeLists.txt users.


** Licence

MIT License

Copyright (c) 2017 Red-Portal

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
